const SearchActionTypes = {
  SEARCH_MOVIE_START: 'SEARCH_MOVIE_START',
  SEARCH_MOVIE_SUCCESS: 'SEARCH_MOVIE_SUCCESS',
  SEARCH_MOVIE_FAILURE: 'SEARCH_MOVIE_FAILURE',
  SEARCH_BY_ID_START: 'SEARCH_BY_ID_START',
  SEARCH_BY_ID_SUCCESS: 'SEARCH_BY_ID_SUCCESS',
  SEARCH_BY_ID_FAILURE: 'SEARCH_BY_ID_FAILURE',
}

export default SearchActionTypes;