const SearchActionTypes = {
  SEARCH_MOVIE_START: 'SEARCH_MOVIE_START',
  SEARCH_MOVIE_SUCCESS: 'SEARCH_MOVIE_SUCCESS',
  SEARCH_MOVIE_FAILURE: 'SEARCH_MOVIE_FAILURE'
}

export default SearchActionTypes;